[
    'Foto kuburan tengah malam berani ga?',
    'Ambil foto bot, jadikan foto profil kamu selama 1 hari',
    'VN nyanyi balonku ada 5',
    'Minum Coca-Cola sampai habis tanpa sendawa selama 30 detik',
    'Makan 1 Cabe tanpa minum, tanpa gorengan selama 2 menit',
    'Celupin hp kamu ke air selama 30 detik',
    'VN *Aku sayang kamu*',
    'Nyanyi potong bebek angsa (VN)',
    'Kirim pesan ke mantan kamu dan bilang _aku masih suka sama kamu_',
    'Telfon crush/pacar sekarang dan ss ke pemain',
    'Pap ke salah satu anggota grup',
    'Pap apa yang di depan kamu',
    'SS recent call whatsapp',
    'Kirim voice note bilang can i call u baby?',
    'Pake foto sule sampe 3 hari',
    'Ketik pake bahasa daerah 24 jam',
    'Ganti nama menjadi _gue anak lucinta luna_ selama 5 jam',
    'Chat ke kontak wa urutan sesuai %batre kamu, terus bilang ke dia _i lucky to hv you_',
    'Prank chat mantan dan bilang *i love u, pgn balikan*',
    'Record voice baca surah al-kautsar',
    'Ganti nama jadi *BOWO* selama 24 jam',
    'Sebutkan tipe pacar mu!',
    'VN *aku mencintaimu*',
    'Kamu harus pap sekarang!',
    'Kamu harus bagi bagi limit, minimal 2 setiap pengguna',
    'Chatingan selama 1 jam harus 4l4Y 8AN93T',
    'Kirim pesan ke mantan kamu dan bilang aku masih suka sama kamu',
    'Telepon crush/pacar sekarang dan screenshot hasilnya ke pemain',
    'Pap ke salah satu anggota grup',
    'Bilang KAMU CANTIK BANGET NGGAK BOHONG ke cowo',
    'Screenshot recent call WhatsApp',
    'Drop emot 🤸💨 setiap mengetik di grup/pc selama 1 hari',
    'Kirim voice note bilang Can I call u baby?',
    'Drop kutipan lagu/quote, lalu tag member yang cocok untuk kutipan itu',
    'Pakai foto Sule sebagai profil selama 3 hari',
    'Ketik menggunakan bahasa daerah selama 24 jam',
    'Ganti nama menjadi gue anak Lucinta Luna selama 5 jam',
    'Chat ke kontak WhatsApp sesuai urutan % baterai kamu, bilang I lucky to have you',
    'Prank chat mantan dan bilang I love you, pengen balikan',
    'Record voice membaca surah Al-Kautsar',
    'Bilang I have a crush on you, mau jadi pacarku nggak? ke lawan jenis terakhir yang kamu chat (WhatsApp/Telegram), tunggu dia bales, lalu screenshot dan drop ke grup',
    'Sebutkan tipe pacar idealmu!',
    'Snap/post foto pacar/crush',
    'Teriak nggak jelas lalu kirim voice note ke grup',
    'Pap mukamu lalu kirim ke salah satu temanmu',
    'Kirim fotomu dengan caption Aku anak pungut',
    'Teriak menggunakan kata kasar sambil voice note lalu kirim ke grup',
    'Teriak Anjimm gabut anjimmm! di depan rumahmu',
    'Ganti nama menjadi BOWO selama 24 jam',
    'Pura-pura kerasukan, contoh: kerasukan maung, belalang, kulkas, dll.'
  ]
