[
    "Pernah suka sama siapa aja? Berapa lama?",
    "Kalau boleh atau kalau mau, di grup/luar grup siapa yang akan kamu jadikan sahabat? (boleh beda/jenis sama)",
    "Apa ketakutan terbesar kamu?",
    "Pernah suka sama orang dan merasa orang itu suka sama kamu juga?",
    "Siapa nama mantan pacar temanmu yang pernah kamu sukai diam-diam?",
    "Pernah nggak nyuri uang nyokap atau bokap? Alasannya?",
    "Hal yang bikin senang pas kamu lagi sedih apa?",
    "Pernah cinta bertepuk sebelah tangan? Kalau pernah, sama siapa? Rasanya gimana?",
    "Pernah jadi selingkuhan orang?",
    "Hal yang paling ditakuti?",
    "Siapa orang yang paling berpengaruh pada kehidupanmu?",
    "Hal membanggakan apa yang kamu dapatkan di tahun ini?",
    "Siapa orang yang bisa membuatmu sange?",
    "Siapa orang yang pernah buatmu sange?",
    "(Bagi yang muslim) pernah nggak salat seharian?",
    "Siapa yang paling mendekati tipe pasangan idealmu di sini?",
    "Suka mabar (main bareng) sama siapa?",
    "Pernah nolak orang? Alasannya kenapa?",
    "Sebutkan kejadian yang bikin kamu sakit hati yang masih diingat!",
    "Pencapaian yang sudah didapat apa aja di tahun ini?",
    "Kebiasaan terburukmu pas di sekolah apa?",
    "Siapa orang yang paling sering kamu pikirkan akhir-akhir ini?",
    "Pernah nggak kamu pura-pura sibuk biar nggak ikut ngumpul?",
    "Apa kebohongan terbesar yang pernah kamu katakan ke orang tua?",
    "Siapa orang yang pernah kamu suka diam-diam, tapi nggak pernah tahu?",
    "Kalau bisa ganti hidup dengan orang lain sehari, kamu pilih siapa dan kenapa?",
    "Apa hal paling kekanak-kanakan yang masih kamu lakukan sampai sekarang?",
    "Pernah nggak kamu merasa iri sama teman sendiri? Ceritakan.",
    "Kalau mantanmu ngajak balikan sekarang, kamu terima atau nggak?",
    "Hal paling gila apa yang pernah kamu lakukan karena cinta?",
    "Pernah stalk mantan atau gebetan sampai sejauh apa?",
    "Kalau ada yang nembak kamu sekarang, siapa yang kemungkinan besar kamu tolak?",
    "Siapa orang yang paling bikin kamu insecure, dan kenapa?",
    "Pernah bohong ke sahabatmu sendiri? Tentang apa?",
    "Hal apa dari dirimu yang paling kamu sembunyikan dari orang lain?",
    "Apa ketakutan terbesar kamu dalam hidup?",
    "Siapa di grup ini yang paling kamu percaya? Dan siapa yang paling nggak?",
    "Kapan terakhir kamu nangis, dan karena apa?",
    "Pernah merasa sendirian padahal banyak orang di sekitarmu? Jelaskan.",
    "Kalau kamu bisa ubah satu keputusan di masa lalu, itu apa?",
    "Apa pendapat jujurmu tentang cinta saat ini?"
]
